### ISSUE TITLE
pod

### ISSUE THREAD

**Issue by syrakozz** [floatlearning/FLWebView#2]
could you pls make it pod

**Comment by steverichey** [comment]
We will consider making this available as a CocoaPod in the future.

**Comment by EgoAleSum** [comment]
"pod install" is not working: seems like the pod has not been published to the CocoaPods registry

**Comment by steverichey** [comment]
@EgoAleSum We have not yet made this available via CocoaPods, although this is a possibility for the future, and we did begin integration in this repository. If you'd like to open a pull request with the CocoaPods integration completed, we'd be happy to merge it in and publish to the registry.
