### ISSUE TITLE
cocoapods can't find 'FLWebView'

### ISSUE THREAD

**Issue by imnak0** [floatlearning/FLWebView#5]
I added the following line into my project's podfile,
 pod 'FLWebView'
but I failed to install it with the error message "[!] Unable to find a specification for `FLWebView`"

would you handle this cocoapods install issue, please?

**Comment by steverichey** [comment]
Unfortunately, we have not had time to make this available as a CocoaPod. However, pull requests to enable this functionality are very much welcome!
